### ISSUE TITLE
aaLog not pulling records when SMC is not viewing logs?

### ISSUE THREAD

**Issue by fledder** [aaOpenSource/aaLog#11]
Have you had an issue where you can't retrieve any logs until you go to SMC - Log Viewer - Default Group - Local?

**Comment by arobinsongit** [comment]
I have not seen this issue but to be frank I have not explicitly tested for it either. Can you describe some steps to recreate?

**Comment by arobinsongit** [comment]
Could not recreate issue.  If you can provide a more detailed description of the steps to reproduce please re-open this issue.  

Close #11

**Comment by arobinsongit** [comment]
Closing Issue
