### ISSUE TITLE
Remove log4net configuration command

### ISSUE THREAD

**Issue by logic-danderson** [aaOpenSource/aaLog#21]
This line should be removed from aaLogReader:

[assembly: log4net.Config.XmlConfigurator(ConfigFile = "log.config", Watch = true)]

In my opinion that belongs in the hosting executable, not the library. The way it stands now the library is hard coded to use log.config, and maybe that's not what the application developer prefers. 

I tested it and logging still works without this line in aaLogReader as long as the hosting app is configured correctly.

**Comment by arobinsongit** [comment]
Merge complete.  Closing Issue.
